# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.5
  - 1
  - nightly
os:
  - windows
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1.8
      os: windows
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: DocMeta, doctest
          using EntropyHub
          DocMeta.setdocmeta!(EntropyHub, :DocTestSetup, :(using EntropyHub); recursive=true)
          doctest(EntropyHub)
          include("docs/make.jl")'
      after_success: skip
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Coveralls.submit(process_folder())'
