# This is a basic workflow to help you get started with Actions

name: Documentation

on:
  push:
    branches:
      - master
      - /^release-.*$/
      - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    tags: '*'
  pull_request:


jobs:
  build:
    permissions:
      actions: write
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          #DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl


#jobs:
#  build:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: julia-actions/setup-julia@latest
#        with:
#          version: '1.8'
#      - name: Install dependencies
#        run: julia --project=docs/ -e 'using Pkg;  Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
#      - name: Build and deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
#          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
#        run: julia --project=docs/ docs/make.jl
